.Dd January 30, 2021
.Dt WCAL 1
.Os
.Sh NAME
.Nm wcal
.Nd ISO weekly calendar
.Sh SYNOPSIS
.Nm
.Op Fl 13yci
.Op Fl d Ar YYYY Ns Op Ar -MM Ns Op Ar -DD
.Sh DESCRIPTION
The
.Nm
utility prints a week-oriented calendar.
Each week is prefixed with its ISO week number.
.Pp
When outputting to a TTY,
the current day, week day, and week are shown in reverse video.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl 1
Show the calendar for the current month.
(This is the default.)
.It Fl 3
Show the calendar for the previous, current, and next month.
.It Fl y
Show the calendar for the whole year.
.It Fl c
Show the calendar for the current week.
.It Fl i
Show the calendar starting from the current week indefinitely.
.It Fl d Ar YYYY Ns Op Ar -MM Ns Op Ar -DD
Show the calendar for a different date than today.
Implies
.Fl y
in case only a year is passed.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr cal 1
.Pp
.Nm
is inspired by this online tool:
.Lk https://demeyere.design/journal/plain-text-calendar
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
.Sh CAVEATS
This program uses a proleptic Gregorian Calendar
and may yield unexpected results before 1752.
The year 0000 starts on a Saturday.
